backend:
  name: git-gateway
  repo: Mainfast/allto
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
  branch: main
  site_domain: location.hostname
  base_url: https://api.netlify.com
  

publish_mode: editorial_workflow
media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "clients" # Used in routes, e.g., /admin/collections/blog
    label: "Clientes" # Used in the UI
    folder: "clients" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", format: 'YYYY-MM-DD hh:mm:ss'}
      - {label: "image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "service" # Used in routes, e.g., /admin/collections/blog
    label: "Serviços" # Used in the UI
    folder: "service" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", format: 'YYYY-MM-DD hh:mm:ss'}
      - {label: "image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
