backend:
  name: github
  repo: Mainfast/allto
  branch: master
  site_domain: https://allto-digital.netlify.app/

publish_mode: editorial_workflow
media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "clientes" # Used in routes, e.g., /admin/collections/blog
    label: "Clientes" # Used in the UI
    folder: "content" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}